apiVersion: v1
kind: Service
metadata:
  name: fdp-client-service
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: fairdata-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
