kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: retain-storageclass
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
