apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triple-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.statefulsets.triple.storage_size }}
