apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fairdata-main
    app.kubernetes.io/type: app
  name: fairdata-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fairdata-main
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fairdata-main
    spec:
      containers:
      - image: fairdata/fairdatapoint:1.12.0
        name: fdp-main
        command: ["/bin/sh", "-c"]  
        args: 
          - /bin/echo "instance:%  clientUrl! http://fdp-client-service%server:%  port! 80%spring:%  data:%    mongodb:%      uri! mongodb://fdp-mongo-service:27017/fdp%repository:%    type! 5%    blazegraph:%        url! http://fdp-triple-service:8080/blazegraph" > ./tmp.yml && sed 's#%#\n#g' tmp.yml > tmp2.yml && sed 's#!#:#g' tmp2.yml > ./application.yml && /usr/local/openjdk-16/bin/java -jar app.jar --spring.profiles.active=production --spring.config.location=classpath:/application.yml,classpath:/application.yml,file:/fdp/application.yml
      nodeSelector:
        cloud.google.com/gke-nodepool: crack-battery-327504-gke-app-pool
