apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: mongo-fair
  name: mongo-fair
spec:
  replicas: 2
  serviceName: fdp-mongo-service
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-fair
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-fair
    spec:
      containers:
      - image: mongo:4.0.12
        name: mongo
        command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - "MainRepSet"
        resources:
          requests:
            cpu: 0.4
            memory: 1000Mi
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
      nodeSelector:
        cloud.google.com/gke-nodepool: crack-battery-327504-gke-data-pool
  volumeClaimTemplates:
  - metadata:
      name: mongo-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
