apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fairdata-client
    app.kubernetes.io/type: app
  name: fairdata-client
spec:
  replicas: {{ .Values.deployments.client.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fairdata-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fairdata-client
    spec:
      containers:
      - image: {{ .Values.deployments.client.image }} 
        name: fdp-client
        ports:
        - containerPort: 80
        env:
        - name: FDP_HOST
          value: fdp-service
        resources:
          requests:
            cpu: {{ .Values.deployments.client.cpu_requests }}
            memory: {{ .Values.deployments.client.memory_requests }}
          limits:
            cpu: {{ .Values.deployments.client.cpu_limits }}
            memory: {{ .Values.deployments.client.memory_limits }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 60
      nodeSelector:
        cloud.google.com/gke-nodepool: app-pool
